### ISSUE TITLE
Adding the presentation slides 

### ISSUE THREAD

**Issue by kzgrzendek** [adamatics/let-the-right-one-in#1]
Hello @manniche,

Thank you for your very interesting talk. Would it be possible to add the presentation slides on the repo, so ze can follow along with the tutorial?

Thank you very much :)

**Comment by manniche** [comment]
Hi @kzgrzendek 
Thanks for the suggestion, I'm on mobile right now but will definitely upload the slides once in vicinity of my laptop 👍

**Comment by manniche** [comment]
Wow! It took me some time to get in vicinity of my laptop. But here I am, And here the presentation is. Thanks
